# Place class zoom levels
[place]
city = 11.5
country = 5
state = 6
town = 12
village = 14
suburb = 14
neighbourhood = 15
quarter = 15
district = 14

# Other layer zoom levels
[layers]
address = 16
landuse = 15
poi = 16
transportation_name = 15
water_name = 13
mountain_peak = 14
park = 14

[default]
zoom = 15

# Search center configuration
[search_center]
use_this = true  # true-set the following as search center on load, false-auto calculate search center

# if you want to permanently change the center for a map,
# you need to MANUALLY edit the config file,
# So, 
# -> experiment and find an appropriate search center 
# -> copy lat, long and zoom values from the browser
# -> register your map file in the following format
# -> paste them here
# -> restart the app
# -> the map will open at the search center and searches will use this search center

[[search_center.perMap]]
fileName = "india.pmtiles"
latitude = 20.0000
longitude = 80.0000
zoom = 4.63

[[search_center.perMap]]
fileName = "malaysia-singapore-brunei.pmtiles"
latitude = 1.4697
longitude = 103.9019
zoom = 9.3

[[search_center.perMap]]
fileName = "nepal.pmtiles"
latitude = 27.5141
longitude = 90.4336
zoom = 7
